### ISSUE TITLE
fitter class

### ISSUE THREAD

**Issue by paigemkelly** [sweverett/CluStR#31]
Should we use the old file for the fit, or rewrite a new one into the clustr.py directly into the fitter class?

**Comment by sweverett** [comment]
Could you say a bit more about what you mean? It looks like the fitter was the following function in the master branch: https://github.com/sweverett/CluStR/blob/master/clustr.py#L286

I'd recommend creating a `fitter` class that takes a `config` in the constructor and has a `fit` class function that takes in a `Data` object (or whatever we decided to call that class - the one that is only the data we want to fit, taken from the full `Catalog`).

Does that make sense?

**Comment by sweverett** [comment]
Something like:
```
class Fitter(object):
    def __init__(self, config):
        ...
    def fit(self, data):
        ...
        (implements the code in `main` here, but ignoring the mantz vs kelly stuff)
```

**Comment by paigemkelly** [comment]
yes, thank you!

**Comment by sweverett** [comment]
One small tip - it's best to keep the issue open until the actual code has been implemented and confirmed to work. That way we can keep talking about it here and the issue status is an accurate reflection of the code!

**Comment by sweverett** [comment]
So I'd keep it open until the `Fitter` class is completed, not just the skeleton code I outlined above.

**Comment by sweverett** [comment]
TODO: 
- Add a line to `main()` to construct `Fitter` object
- Only pass `Data` to fitter when calling `fitter.fit(data)`
