### ISSUE TITLE
plotting

### ISSUE THREAD

**Issue by paigemkelly** [sweverett/CluStR#34]
Should we build off the plotlib.py code you already wrote? or start fresh with the plotting. Jose and I have only done basic plots, so we were gonna take a class or something to figure out how to do that.

**Comment by sweverett** [comment]
Yes it's perfectly ok to use code we already wrote!

**Comment by paigemkelly** [comment]
but should we rewrite it or is it fine as is and we should just move it directly into clustr.py?

**Comment by sweverett** [comment]
Personally I think it's better not to have one giant file with all the code. Split things up thematically/conceptually - there's `clustr.py` which defines what it means to be a CluStR pipeline and how to run it, there's `plotlib.py` which has all of the plotting functions, and there's `reglib.py` which has all of the regression functions.

**Comment by sweverett** [comment]
It might not be obivious why that's helpful here. But when you're working on projects with tens of thousands of lines of code (or more!), it's a huge pain if you haven't split up code into easily understandable chunks.
