### ISSUE TITLE
Flags for Rewrite

### ISSUE THREAD

**Issue by jjobel** [sweverett/CluStR#41]
I was thinking of making a function that is not dependent on terminal arguments but rather relies on the `param.config` file such that the user sets the flags they want applied to `True` in the `param.config` file. Since the `param.config` file contains many boolean values, the function would need a list of flag column labels to reference. If such column label is set to `True` in the config file, then the function proceeds to remove all rows that contain [row, col] values we don't want included in our analysis. 

For example, suppose we have this data frame `df`:

```
|Name       | Merger |
| catalog_1 |    0   |
| catalog_2 |    1   |
| catalog_3 |    0   |

```

0 means not a merger
1 means yes a merger

If user sets `merger=True` in the `param.config`, then we want to remove all rows with `df["merger"] = 1`. We would then have a new dataframe `df` of only good rows. 

```
|Name       | Merger |
| catalog_1 |    0   |
| catalog_3 |    0   |

```

I understand how to reference the config file and check if labels are set to `True`. I've uploaded a naive approach for doing that but I'm having a hard time figuring out how to cut the rows from the data. I've been referencing the `master` branch for inspiration but I get lost on how ` mask = np.zeros(len(data), dtype=bool)` and `mask |= cut` is being used in both the `create_cuts(data, flags)` function and `get_data(options)` function.

**Comment by jjobel** [comment]
(UPDATE)
First flag test was successful. I used the `merger` flag to test out the function and 61 out of 1092 rows were accepted for analysis.
 
![1_14_21_Clustr_Flag_Outputs](https://user-images.githubusercontent.com/43651622/104664447-1c930100-5684-11eb-8967-e096701c57db.jpg)

I'll need to cross verify If I'm actually removing the correct rows using pandas in a separate session. Once that is finished I'll continue working to include other flag types and update when that works.

**Comment by jjobel** [comment]
Check out 0d935a3a512f654f03323d0e051a46bf1d7119bf as a possible final draft for `clustr.py`. 

This is the output of the above version. 

![Screenshot 2021-01-19 162049](https://user-images.githubusercontent.com/43651622/105109930-5ee88380-5a72-11eb-95a2-6488cdcfef43.jpg)

**Comment by paigemkelly** [comment]
Removed 89 clusters due to `Serendipitous` flag of type `True`
Removed 62 clusters due to `merger` flag of type `True`
NOTE: `Removed` counts may be redundant, as some data fail multiple flags.
Accepted 245 data out of 1092
mean x error: 5.60469675e+42
mean y error: 3.874964
Using Kelly Algorithm...

Making Plots...
Done!

We just need to find out if cutoff refers to detected or not in the catalog I think.

**Comment by jjobel** [comment]
(Update) 

What I've done is completely reworked how the boolean flag was done in the version referenced by me above. Boolean flags are explicitly in the `config.yml` file and not hard coded in `clustr.py`. I will upload both files as soon as I'm done reworking the `cutoff flags` in `clustr.py` (later tonight).

**Comment by jjobel** [comment]
(Update 2) 

Okay so I've uploaded `clustr.py` with its newly and improved `create_cuts()` method. This was done to avoid hard coding the flags in the source code as @sweverett advised. To replace the previous strategy of having to referencing a list to know which flags to apply, I've created nested dictionaries for both the boolean flags and range flags in the new `config.yml` file. The content in the `config.yml` file is exactly the same as `param.config` file with the following dictionary structure. 

For example, 

```
Boolean: {
    key1: value1,
    key2: value2,
    key3: value3,
    key4: value4
}

Range: {
    keyA: {
        keyB: {
            keyC: valueC,
            keyD: valueD,
            keyE: valueE}},
    keyF: {
        keyG: {
            keyH: valueH,
            keyI: valueI,
            keyJ: valueJ}}
}
````

Doing this gives the user the freedom of adding in a new flag type into the config file without having to mess with the source code. 

Below is the result I get when running the code:

![Screenshot 2021-01-28 230533](https://user-images.githubusercontent.com/43651622/106245859-10e62500-61c2-11eb-9e8b-3ce57563b4f1.jpg)

-----------------------

The cutoff section in `create_cuts()` is not finished yet. I'm hoping to have it done by tomorrow afternoon.

**Comment by sweverett** [comment]
Great! That looks like what I was originally envisioning. Basically the approach we're taking is to "trust" that the user is passing a valid column name, but to have it fail loudly if it isn't so that they are aware they did something wrong. This will make it much easier for future people down the line to make cuts based off of new columns we haven't thought of yet, while also keeping a history of config files that show exactly how each run was done.

**Comment by jjobel** [comment]
Went ahead and did some further changes to `config.yml`.  The notation I used in the example above was not the correct for a YAML file so I went ahead and simplified it 😅 along with some instructions on how to add new flags.
