### ISSUE TITLE
to do

### ISSUE THREAD

**Issue by paigemkelly** [sweverett/CluStR#43]
- [x] put the 3 masks into one
- [x] move the list of allowed flags (boolean, range, snr) into the config file and access it from there
- [x] reformat the config file to yaml format
- [x] add at the end of each flag statement something that removes the NaNs
- [x] double check error handling with Aryas code
- [x] check for mistake that is making b, m, sigma different
- [x] make a True/False for boolean flags

**Comment by jjobel** [comment]
Reworked the Boolean flag to config. I'll continue this explanation in issue #41 to avoid multiple flag issues.

**Comment by jjobel** [comment]
Issues List Complete!
